BUG: Only upload *.whl Python packaging artifacts
Wildcards are supported in actions/upload-artifact@v3.

Move Windows wheels to avoid:

  Error: Invalid pattern '../../im/dist/*whl'. Relative pathing '.' and '..' is not allowed.

For itk-wasm, this was picking up the NPM package artifacts instead of
the wheels.